import 'package:flutter/material.dart';

import 'itheme.dart';

class LightTheme implements Itheme {
  @override
  ThemeData theme = ThemeData(
    colorScheme: const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFFDC5D5A),
        onPrimary: Color(0xFFFFFFFF),
        secondary: Color(0xFFAC3306),
        onSecondary: Color(0xFFFFFFFF),
        error: Color(0xFFB00020),
        errorContainer: Color(0xFFFCD8DF),
        inverseSurface: Color(0xFF2B1A1A),
        inversePrimary: Color(0xFFFFF4F3),
        onErrorContainer: Color(0xFF000000),
        onInverseSurface: Color(0xFFFFFFFF),
        onPrimaryContainer: Color(0xFF000000),
        onSecondaryContainer: Color(0xFF000000),
        onTertiary: Color(0xFFFFFFFF),
        onSurfaceVariant: Color(0xFF000000),
        onTertiaryContainer: Color(0xFF000000),
        outline: Color(0xFF4D4D4D),
        primaryContainer: Color(0xFFD0E4FF),
        secondaryContainer: Color(0xFFFFDBCF),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFFDC5D5A),
        surfaceVariant: Color(0xFFF5D5D4),
        tertiary: Color(0xFF006875),
        tertiaryContainer: Color(0xFF95F0FF),
        onError: Color(0xFFFFFFFF),
        background: Color(0xFFFAEAE9),
        onBackground: Color(0xFF000000),
        surface: Color(0xFFFAEAE9),
        onSurface: Color(0xFF000000)),
    brightness: Brightness.light,
    primaryColor: const Color(0xFF2196F3),
    primaryColorDark: const Color(0xFF1976D2),
    primaryColorLight: const Color(0xFFBBDEFB),
    secondaryHeaderColor: const Color(0xFFE3F2FD),
    toggleableActiveColor: const Color(0xFF1E88E5),
    bottomAppBarColor: const Color(0xFFFFFFFF),
    errorColor: const Color(0xFFD32F2F),
    canvasColor: const Color(0xFFFAFAFA),
    cardColor: const Color(0xFFFFFFFF),
    scaffoldBackgroundColor: const Color(0xFFFAFAFA),
    dialogBackgroundColor: const Color(0xFFFFFFFF),
    indicatorColor: const Color(0xFF2196F3),
    disabledColor: const Color(0x61000000),
    hoverColor: const Color(0x0A000000),
    highlightColor: const Color(0x66BCBCBC),
    focusColor: const Color(0x1F000000),
    splashColor: const Color(0x66C8C8C8),
    shadowColor: const Color(0xFF000000),
    hintColor: const Color(0x99000000),
    appBarTheme: const AppBarTheme(
        elevation: 1,
        backgroundColor: Color(0xFFFFFFFF),
        centerTitle: false,
        iconTheme: IconThemeData(color: Color(0XFF000000), size: 20)),
    selectedRowColor: const Color(0xFFF5F5F5),
    unselectedWidgetColor: const Color(0x8A000000),
    dividerColor: const Color(0x1F000000),
  );
}
